services:
  postgres:
    image: postgres:14
    container_name: addvocate-postgres-db
    env_file:
      - ./.env
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - addvocate-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: addvocate-backend
    env_file:
      - ./.env
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - addvocate-network
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: addvocate-frontend
    env_file:
      - ./.env
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - addvocate-network
    restart: always
    environment:
      - VITE_API_URL=http://127.0.0.1:3000
    command: npm run dev

networks:
  addvocate-network:
    driver: bridge

volumes:
  postgres-data:
